"""add foreign key rates -> currencies

Revision ID: 3bab9ef88f1f
Revises: dde68e99685a
Create Date: 2025-12-16 15:17:53.424459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bab9ef88f1f'
down_revision = 'dde68e99685a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
